# -*- coding: utf-8 -*-
"""plotly_20221104.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VB-dD1ofm96G6sNqtAxrrl4TvDgofFxd

# Plotly互動式資料視覺化

- [[Day 22] Python 視覺化解釋數據 - Plotly Express]()
- [Plotly Open Source Graphing Library for Python](https://plotly.com/python/)

### 參考資料[Creating and Updating Figures in Python](https://plotly.com/python/creating-and-updating-figures/)
"""

!pip install plotly

fig = dict({
    "data": [{"type": "bar",
              "x": [1, 2, 3],
              "y": [1, 3, 2]}],
    "layout": {"title": {"text": "A Figure Specified By Python Dictionary"}}
})

# To display the figure defined by this dict, use the low-level plotly.io.show function
import plotly.io as pio

pio.show(fig)

import plotly.graph_objects as go

fig = go.Figure(
    data=[go.Bar(x=[1, 2, 3], y=[1, 3, 2])],
    layout=go.Layout(
        title=go.layout.Title(text="A Figure Specified By A Graph Object")
    )
)

fig.show()

import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species", title="A Plotly Express Figure")

# If you print the figure, you'll see that it's just a regular figure with data and layout
# print(fig)

fig.show()